# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f5743ca15a5debb14ed35151684cf4930e917bade66975d434dc23c04f4491c488b1dcaf43253746156645bdcbd9ecd7f4b9ea442235fc38827a82039d39ed5

test:
  secret_key_base: fcac62e6d7438d62ba72cdbed92b2a0a06364d9f406b9a57e929c40ead5a1925b58a315ed170936380464b1cd12885995e24faf4e86a5eec083fcf0f248a1354

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
